### ISSUE TITLE
Hériter Alpha

### ISSUE THREAD

**Issue by Jissse** [Rainbox-dev/OCA#1]
À ajouter 

Dans Krita
![unknown2](https://user-images.githubusercontent.com/21180405/98843987-f9fa2700-244b-11eb-825c-0cbb5ddeeef5.png)

Dans After
![unknown](https://user-images.githubusercontent.com/21180405/98844001-ff577180-244b-11eb-8fe7-03cc8a0f1304.png)

**Comment by Nico-Duduf** [comment]
Krita: Node.inheritAlpha() https://api.kde.org/appscomplete-api/krita-apidocs/libs/libkis/html/classNode.html#a689a98bf668b87aef051d7af4f7d8816

Ae: AVLayer.preserveTransparency https://ae-scripting.docsforadobe.dev/layers/avlayer/#avlayer-preservetransparency
